# spring
spring:
  datasource:
    url: jdbc:mysql://192.168.100.120:3307/springboot-shiro-vue?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #如果使用字符串表示，用这行设置格式
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false #使用时间戳，使用数值timestamp表示日期
logging:
  level:
    org.middlesoft.shiro: debug

server:
  port: 8080